### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by dthierry** [dthierry/k_aug#30]
So far: 
 - issue with asl (a.exe)
 - issue with scotch: zlib1g gnu?
 - issue with mumps: correct .dll.a and metis dir
 - issue with amplsolver.dll.a
 - issue with openblas

**Comment by mchlshort** [comment]
Hi @dthierry, when attempting to install k_aug on Windows 8.1 using cygwin I get the following issues:

for ASL:

"Making ..
cc -c -O -DASL_NO_FPINITMT fpinit.c
cc -O arithchk.c fpinit.o -lm ||\
 cc -DNO_LONG_LONG -O arithchk.c fpinit.o -lm ||\
 cc -DNO_SSIZE_T -O arithchk.c fpinit.o -lm ||\
 cc -DNO_LONG_LONG -DNO_SSIZE_T -O arithchk.c fpinit.o -lm
./a.out >arith.h
/bin/sh: ./a.out: No such file or directory
make: *** [makefile.u:236: arith.h] Error 127"

Everything else seemed ok until the final make:

"Scanning dependencies of target k_aug
[  5%] Building C object CMakeFiles/k_aug.dir/src/k_aug/assemble_rhs_dcdp.c.o
In file included from /home/Michael/k_aug/src/k_aug/assemble_rhs_dcdp.h:23:0,
                 from /home/Michael/k_aug/src/k_aug/assemble_rhs_dcdp.c:22:
/home/Michael/k_aug/thirdparty/asl/solvers/asl.h:26:10: fatal error: stdio1.h: N                            o such file or directory
 #include "stdio1.h"
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/k_aug.dir/build.make:63: CMakeFiles/k_aug.dir/src/k_aug                            /assemble_rhs_dcdp.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/k_aug.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
"

Any thoughts on this?

**Comment by dthierry** [comment]
Hi Mike, these issues on a separate branch. There is still a couple tests that I wanted to make before the pull request. But I will have it ready soon.

**Comment by dthierry** [comment]
kaug/master should work on windows now! Please, check the instructions for further details.

**Comment by mchlshort** [comment]
Hi @dthierry , I can confirm that k_aug/master is working on Windows now. I have attached an installation guide for anyone looking for step-by-step instructions. I can't upload directly to the repo, but you are welcome to upload it. I included both pdf and doc for if you need to make changes.

[Installation guide for k_aug.pdf](https://github.com/dthierry/k_aug/files/2573054/Installation.guide.for.k_aug.pdf)

[Installation guide for k_aug.docx](https://github.com/dthierry/k_aug/files/2573055/Installation.guide.for.k_aug.docx)

**Comment by dthierry** [comment]
Thanks Mike.  I will upload them!.

**Comment by dthierry** [comment]
@mchlshort you can check this python [script](https://github.com/dthierry/k_aug/blob/master/test/pyomo_/sens_kaug_dcdp.py) for the example on how to use `k_aug` to generate the dxdp matrix.

**Comment by mchlshort** [comment]
Thank you, kind sir.

**Comment by mchlshort** [comment]
Hi @dthierry , have you attempted to use k_aug on Windows for any larger problem? It performs a lot slower on my Windows machine. Something that takes seconds on my Linux PC has taken significant time on my Windows PC. Any ideas why that might be?
